export const resumes = [
  {
    id: 1,
    userId: 1,
    name: 'Александра',
    secondName: 'Дмитриевна',
    lastName: 'Липиснкая',
    birthday: '13.05.1988',
    location: 'Тула',
    profileId: 1,
    tagsId: [1, 2, 3, 4, 5]
  },
  {
    id: 2,
    userId: 2,
    name: 'Павел',
    secondName: 'Анатольевич',
    lastName: 'Минаев',
    birthday: '01.01.1980',
    location: 'Москва',
    profileId: 1,
    tagsId: [6, 7, 8, 9, 10]
  },
  {
    id: 3,
    userId: 3,
    name: 'Антон',
    secondName: 'Серргеевич',
    lastName: 'Чембуров',
    birthday: '01.01.1980',
    location: 'Москва',
    profileId: 1,
    tagsId: [1, 2, 9, 10, 11, 12]
  },
  {
    id: 4,
    userId: 4,
    name: 'Иван',
    secondName: 'Иванович',
    lastName: 'Васнецов',
    birthday: '01.01.1980',
    location: 'Москва',
    profileId: 2,
    tagsId: [10, 11, 12, 13, 14, 15]
  },
  {
    id: 5,
    userId: 5,
    name: 'Инесса',
    secondName: 'Владимировна',
    lastName: 'Зайцева',
    birthday: '01.01.1980',
    location: 'Москва',
    profileId: 3,
    tagsId: [16, 17, 18, 19, 20, 21, 22]
  },
  {
    id: 6,
    userId: 6,
    name: 'Альфред',
    secondName: 'Игоревич',
    lastName: 'Столяров',
    birthday: '01.01.1980',
    location: 'Москва',
    profileId: 3,
    tagsId: [1, 3, 4]
  },
  {
    id: 7,
    userId: 7,
    name: 'Дмитрий',
    secondName: 'Борисович',
    lastName: 'Ентин',
    birthday: '01.01.1980',
    location: 'Москва',
    profileId: 1,
    tagsId: [1, 3, 4, 5, 6, 7]
  },
  {
    id: 8,
    userId: 8,
    name: 'Антон',
    secondName: 'Юрьевич',
    lastName: 'Чекалин',
    birthday: '01.01.1980',
    location: 'Москва',
    profileId: 1,
    tagsId: [1, 3, 4, 5, 6, 7]
  },
  {
    id: 9,
    userId: 9,
    name: 'Алена',
    secondName: 'Юрьевна',
    lastName: 'Карпова',
    birthday: '01.01.1980',
    location: 'Москва',
    profileId: 1,
    tagsId: [1, 3, 4, 5, 6, 7]
  },
  {
    id: 10,
    userId: 10,
    name: 'Дарья',
    secondName: 'Дмитриевна',
    lastName: 'Липинская',
    birthday: '01.01.1980',
    location: 'Москва',
    profileId: 1,
    tagsId: [1, 3, 4, 5, 6, 7]
  },
  {
    id: 11,
    userId: 11,
    name: 'Вадим',
    secondName: 'Викторович',
    lastName: 'Вознесенский',
    birthday: '01.01.1980',
    location: 'Москва',
    profileId: 1,
    tagsId: [1, 3, 4, 5, 6, 7]
  },
  {
    id: 12,
    userId: 12,
    name: 'Илья',
    secondName: 'Михайлович',
    lastName: 'Сорокин',
    birthday: '01.01.1980',
    location: 'Москва',
    profileId: 1,
    tagsId: [1, 3, 4, 5, 6, 7]
  },
  {
    id: 13,
    userId: 13,
    name: 'Андрей',
    secondName: 'Юрьевич',
    lastName: 'Эм',
    birthday: '01.01.1980',
    location: 'Москва',
    profileId: 1,
    tagsId: [1, 3, 4, 5, 6, 7]
  },
  ,
  {
    id: 14,
    userId: 14,
    name: 'Илья',
    secondName: 'Игоревич',
    lastName: 'Абрамов',
    birthday: '01.01.1980',
    location: 'Москва',
    profileId: 1,
    tagsId: [1, 3, 4, 5, 6, 7]
  },
];
