export const tags = [
  { id: 1, value: 'JavaScript'},
  { id: 2, value: 'HTML5'},
  { id: 3, value: 'CSS3'},
  { id: 4, value: 'LESS'},
  { id: 5, value: 'SASS'},
  { id: 6, value: 'GULP'},
  { id: 7, value: 'GRUNT'},
  { id: 8, value: 'Angular JS'},
  { id: 9, value: 'Angular'},
  { id: 10, value: 'React'},
  { id: 11, value: 'React Native'},
  { id: 12, value: 'VueJs'},
  { id: 13, value: 'JQuery'},
  { id: 14, value: 'PHP'},
  { id: 15, value: 'Java'},
  { id: 16, value: 'Python'},
  { id: 17, value: 'Elastic Search'},
  { id: 18, value: 'Sphinx'},
  { id: 19, value: 'C#'},
  { id: 20, value: 'C++'},
  { id: 21, value: 'ASP.NET'},
  { id: 22, value: 'Docker'},
  { id: 23, value: 'Npm'},
  { id: 24, value: 'Node JS'},
  { id: 25, value: 'Webpack'},
  { id: 26, value: 'Type Script'},
  { id: 27, value: 'Coffeescript'},
  { id: 28, value: 'Rust'},
  { id: 29, value: 'Golang'},
  { id: 30, value: 'Nginx'},
  { id: 31, value: 'Apache'},
  { id: 32, value: 'AJAX'},
  { id: 33, value: 'JS WEB API'},
  { id: 34, value: 'MySQL'},
  { id: 35, value: 'MSSQL'},
  { id: 36, value: 'MSSQL'},
  { id: 37, value: 'Postgres'},
  { id: 38, value: 'XML'},
  { id: 39, value: 'SOAP'},
  { id: 40, value: 'JSON'},
  { id: 41, value: 'Objective C'},
  { id: 42, value: 'Lisp'},
  { id: 43, value: 'Pascal'},
  { id: 44, value: 'RebbitMQ'},
  { id: 45, value: 'Redis'},
  { id: 46, value: 'MongoDB'},
  { id: 47, value: 'Vuex'},
  { id: 48, value: 'REDUX'},
  { id: 49, value: 'Ngrx'},
  { id: 50, value: 'RxJs'},
  { id: 51, value: 'Jsx'},
  { id: 52, value: 'Mobx'},
  { id: 53, value: 'Express'},
  { id: 54, value: 'Git'},
  { id: 55, value: 'API Yandex maps'},
  { id: 56, value: 'API Google maps'},
  { id: 57, value: 'Sentry'},
  { id: 58, value: 'API Yandex market'},
  { id: 59, value: 'ESIA'},
  { id: 60, value: 'OAuth2.0'},
  { id: 61, value: 'Stylus'},
  { id: 62, value: 'Jade'},
  { id: 63, value: 'Mustache'},
  { id: 64, value: 'Django'},
  { id: 65, value: 'Spring framework'},
  { id: 66, value: 'Laravel'},
  { id: 67, value: 'Symfony'},
  { id: 68, value: 'Lumen'},
  { id: 69, value: 'Yii2'},
];
