import {Role} from '../_enums';

export const users = [
  { id: 1, username: 'alipinskaya', password: 'Eevei9xe', role: Role.Admin },
  { id: 2, username: 'user', password: 'user', role: Role.User },
  { id: 3, username: 'user1', password: 'user', role: Role.User },
  { id: 4, username: 'user2', password: 'user', role: Role.User },
  { id: 5, username: 'user3', password: 'user', role: Role.User },
  { id: 6, username: 'user4', password: 'user', role: Role.User },
  { id: 7, username: 'user5', password: 'user', role: Role.User },
  { id: 8, username: 'user6', password: 'user', role: Role.User },
  { id: 9, username: 'user7', password: 'user', role: Role.User },
  { id: 10, username: 'user8', password: 'user', role: Role.User },
  { id: 11, username: 'user9', password: 'user', role: Role.User },
  { id: 12, username: 'user10', password: 'user', role: Role.User },
  { id: 13, username: 'user11', password: 'user', role: Role.User },
  { id: 14, username: 'user12', password: 'user', role: Role.User },
  { id: 15, username: 'user13', password: 'user', role: Role.User },
  { id: 16, username: 'user14', password: 'user', role: Role.User },
  { id: 17, username: 'user15', password: 'user', role: Role.User },
  { id: 18, username: 'user16', password: 'user', role: Role.User },
  { id: 19, username: 'user17', password: 'user', role: Role.User },
  { id: 20, username: 'user18', password: 'user', role: Role.User },
  { id: 21, username: 'user19', password: 'user', role: Role.User },
  { id: 22, username: 'user20', password: 'user', role: Role.User },
  { id: 23, username: 'user21', password: 'user', role: Role.User },
  { id: 24, username: 'user22', password: 'user', role: Role.User },
  { id: 25, username: 'user23', password: 'user', role: Role.User },
  { id: 26, username: 'user24', password: 'user', role: Role.User },
  { id: 27, username: 'user25', password: 'user', role: Role.User },
  { id: 28, username: 'user26', password: 'user', role: Role.User },
  { id: 29, username: 'user27', password: 'user', role: Role.User },
  { id: 30, username: 'user28', password: 'user', role: Role.User },
  { id: 31, username: 'user29', password: 'user', role: Role.User },
  { id: 32, username: 'user30', password: 'user', role: Role.User },
  { id: 33, username: 'user31', password: 'user', role: Role.User },
  { id: 34, username: 'user32', password: 'user', role: Role.User },
];
